catalog:
  local:
    uri: sqlite:////mnt/c/dev/data_pipelines_apache_examples/iceberg/iceberg_catalog/catalog.db
    warehouse: file:////mnt/c/dev/data_pipelines_apache_examples/iceberg/iceberg_catalog